Сверстал домашнюю страницу для mobile
egorovow/twitter pull request #2
Opened 2023-01-24 20:36 UTC by egorovow

2023-01-27 08:29 UTC, burtovoy requested changes

2023-01-27 08:29 UTC, burtovoy commented on postSize.js
>  function postSize(message) {
Этого файла (изменений) не должно быть в этом PR

2023-01-27 08:29 UTC, burtovoy commented on styles/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
Давай попробуем без этого файла

2023-01-27 14:00 UTC, egorovow commented on postSize.js
>  function postSize(message) {
Удалил

2023-01-27 14:00 UTC, egorovow commented on styles/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
Убрал этот файл

2023-01-27 14:18 UTC, burtovoy requested changes
Почти все ок. Нужно убрать файл postSize из этого коммита (удаление – это тоже изменение). Он тут вылез потому что ветка сравнивается с master, а там он есть.

2023-01-30 09:37 UTC, burtovoy requested changes
Здесь не должно быть удаления файла PostSize
Момент по-поводу GitHub. 

Бывает такое что присылается пиар, а там удален файл, который не имеет отношения к данной задаче. Удаление файла - это тоже изменение. Т.е. этого изменения не должно быть в текущем пиар.

Что делать? Нужно чтобы удаления файл не было в PR

Т.е. он сравнивает ветку master с текущей веткой который вы присылаете. Нужно сделать так, чтобы этих изменений не было в master, т.е. удалить их там

2023-01-31 17:39 UTC, egorovow commented
Удалил файл postSize.js в ветке master

2023-02-01 10:31 UTC, merged